# Generated by Django 5.2.7 on 2026-01-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
